/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
If you want to view the source, please visit the github repository
*/


// main.js
var { Plugin, MarkdownRenderChild } = require("obsidian");
var STYLE_ID = "wave-analyzer-plugin-style";
var PLAY_ICON = `
  <svg viewBox="0 0 24 24" aria-hidden="true">
    <path d="M8 5.5v13l10-6.5z"></path>
  </svg>
`;
var STOP_ICON = `
  <svg viewBox="0 0 24 24" aria-hidden="true">
    <rect x="7" y="7" width="10" height="10" rx="1.5"></rect>
  </svg>
`;
var ANALYSIS_ICON = `
  <svg viewBox="0 0 24 24" aria-hidden="true">
    <path d="M3 15h5V8h4v8h4v-6h5" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="square" stroke-linejoin="miter"></path>
  </svg>
`;
var RESOLUTION_OPTIONS = [256, 512, 1024, 2048, 4096, 8192];
var DEFAULT_RESOLUTION_INDEX = 1;
var CANVAS_HEIGHT = 210;
var RULER_HEIGHT = 18;
var PLAYBAR_WIDTH = 5;
var MIN_FUNDAMENTAL_HZ = 60;
var MAX_FUNDAMENTAL_HZ = 2e3;
var MAX_HARMONICS = 8;
var WaveAnalyzerRenderChild = class extends MarkdownRenderChild {
  constructor(containerEl, cleanup) {
    super(containerEl);
    this.cleanup = cleanup;
  }
  onunload() {
    this.cleanup();
  }
};
function clamp(value, min, max) {
  return Math.max(min, Math.min(max, value));
}
function alphaColor(rgb, alpha, fallback) {
  const base = rgb && rgb.includes(",") ? rgb : fallback;
  return `rgba(${base}, ${alpha})`;
}
function formatTime(seconds) {
  const safeSeconds = Number.isFinite(seconds) ? Math.max(0, seconds) : 0;
  const totalMilliseconds = Math.round(safeSeconds * 1e3);
  const mins = Math.floor(totalMilliseconds / 6e4);
  const secs = Math.floor(totalMilliseconds % 6e4 / 1e3);
  const millis = totalMilliseconds % 1e3;
  return `${mins.toString().padStart(2, "0")}:${secs.toString().padStart(2, "0")}:${millis.toString().padStart(3, "0")}`;
}
function formatRulerTime(seconds) {
  const wholeSeconds = Math.max(0, Math.floor(seconds));
  const mins = Math.floor(wholeSeconds / 60);
  const secs = wholeSeconds % 60;
  return `${mins}:${secs.toString().padStart(2, "0")}`;
}
function highestPowerOfTwo(value) {
  return 2 ** Math.floor(Math.log2(Math.max(2, value)));
}
function createHannWindow(size) {
  const windowValues = new Float32Array(size);
  for (let i = 0; i < size; i++) {
    windowValues[i] = 0.5 * (1 - Math.cos(2 * Math.PI * i / (size - 1)));
  }
  return windowValues;
}
function smoothSeries(values, passes = 3) {
  if (values.length < 3 || passes <= 0) {
    return values.slice();
  }
  let current = values.slice();
  for (let pass = 0; pass < passes; pass++) {
    const next = current.slice();
    for (let i = 1; i < current.length - 1; i++) {
      next[i] = (current[i - 1] + current[i] + current[i + 1]) / 3;
    }
    current = next;
  }
  return current;
}
function fft(real, imag) {
  const n = real.length;
  if (n <= 1) {
    return;
  }
  const evenReal = new Float32Array(n / 2);
  const evenImag = new Float32Array(n / 2);
  const oddReal = new Float32Array(n / 2);
  const oddImag = new Float32Array(n / 2);
  for (let i = 0; i < n / 2; i++) {
    evenReal[i] = real[2 * i];
    evenImag[i] = imag[2 * i];
    oddReal[i] = real[2 * i + 1];
    oddImag[i] = imag[2 * i + 1];
  }
  fft(evenReal, evenImag);
  fft(oddReal, oddImag);
  for (let k = 0; k < n / 2; k++) {
    const theta = -2 * Math.PI * k / n;
    const cosTheta = Math.cos(theta);
    const sinTheta = Math.sin(theta);
    const twiddleReal = cosTheta * oddReal[k] - sinTheta * oddImag[k];
    const twiddleImag = sinTheta * oddReal[k] + cosTheta * oddImag[k];
    real[k] = evenReal[k] + twiddleReal;
    imag[k] = evenImag[k] + twiddleImag;
    real[k + n / 2] = evenReal[k] - twiddleReal;
    imag[k + n / 2] = evenImag[k] - twiddleImag;
  }
}
function estimateHarmonicity(powerSpectrum, sampleRate, fftSize, totalPower) {
  if (totalPower <= 0) {
    return 0;
  }
  const minBin = Math.max(
    1,
    Math.floor(MIN_FUNDAMENTAL_HZ * fftSize / sampleRate)
  );
  const maxBin = Math.min(
    powerSpectrum.length - 1,
    Math.floor(
      Math.min(MAX_FUNDAMENTAL_HZ, sampleRate / 4) * fftSize / sampleRate
    )
  );
  if (maxBin <= minBin) {
    return 0;
  }
  let bestBin = minBin;
  let bestScore = 0;
  for (let bin = minBin; bin <= maxBin; bin++) {
    let score = powerSpectrum[bin];
    for (let harmonic = 2; harmonic <= 4; harmonic++) {
      const harmonicBin = bin * harmonic;
      if (harmonicBin >= powerSpectrum.length) {
        break;
      }
      score *= powerSpectrum[harmonicBin] + 1e-12;
    }
    if (score > bestScore) {
      bestScore = score;
      bestBin = bin;
    }
  }
  if (bestScore <= 0) {
    return 0;
  }
  let harmonicEnergy = 0;
  const harmonicCount = Math.min(
    MAX_HARMONICS,
    Math.floor((powerSpectrum.length - 1) / bestBin)
  );
  for (let harmonic = 1; harmonic <= harmonicCount; harmonic++) {
    const centerBin = bestBin * harmonic;
    for (let spread = -1; spread <= 1; spread++) {
      const bin = centerBin + spread;
      if (bin > 0 && bin < powerSpectrum.length) {
        harmonicEnergy += powerSpectrum[bin];
      }
    }
  }
  return clamp(Math.sqrt(harmonicEnergy / totalPower), 0, 1);
}
module.exports = class WaveAnalyzer extends Plugin {
  async onload() {
    this.injectStyles();
    this.registerMarkdownCodeBlockProcessor("wa", async (content, el, ctx) => {
      try {
        let updateRegion2 = function() {
          if (!audioBuffer || visualizationMode !== "waveform" || !hasLoopRegion()) {
            regionDiv.style.display = "none";
            return;
          }
          const dpr = window.devicePixelRatio || 1;
          const width = canvas.width / dpr;
          const startPx = Math.min(regionStart, regionEnd) / audioBuffer.duration * width;
          const endPx = Math.max(regionStart, regionEnd) / audioBuffer.duration * width;
          regionDiv.style.left = `${startPx}px`;
          regionDiv.style.width = `${Math.max(endPx - startPx, 1)}px`;
          regionDiv.style.display = "block";
        };
        var updateRegion = updateRegion2;
        const match = content.match(/\[\[(.+?)\]\]/);
        if (!match) {
          throw new Error("Invalid format. Use: wa\\n [[filename.mp3]]");
        }
        const filename = match[1];
        const linkpath = this.app.metadataCache.getFirstLinkpathDest(
          filename,
          ctx.sourcePath
        );
        if (!linkpath) {
          throw new Error(`File not found: ${filename}`);
        }
        const isInSlide = el.closest(".reveal") !== null;
        if (isInSlide) {
          const bgContainer = el.createDiv({ cls: "slide-background" });
          bgContainer.style.position = "absolute";
          bgContainer.style.width = "100%";
          bgContainer.style.height = "100%";
          bgContainer.style.top = "0";
          bgContainer.style.left = "0";
          bgContainer.style.zIndex = "-1";
          if (el.parentElement) {
            el.parentElement.insertBefore(bgContainer, el);
          }
          el = bgContainer;
        }
        const container = el.createDiv({ cls: "wave-analyzer-container" });
        const stage = container.createDiv({ cls: "wave-analyzer-stage" });
        const canvas = stage.createEl("canvas", {
          cls: "wave-analyzer-canvas"
        });
        const spectrogram = stage.createEl("canvas", {
          cls: "wave-analyzer-spectrogram"
        });
        const regionDiv = stage.createEl("div", {
          cls: "wave-analyzer-region"
        });
        const tooltip = stage.createEl("div", { cls: "wave-analyzer-tooltip" });
        const controls = container.createDiv({ cls: "wave-analyzer-controls" });
        const leftControls = controls.createDiv({
          cls: "wave-analyzer-buttons"
        });
        const playButton = leftControls.createEl("button", {
          cls: "wave-analyzer-play play"
        });
        const modeButton = leftControls.createEl("button", {
          cls: "wave-analyzer-mode",
          text: "W"
        });
        const analysisButton = leftControls.createEl("button", {
          cls: "wave-analyzer-analysis"
        });
        const resolutionButton = leftControls.createEl("button", {
          cls: "wave-analyzer-resolution",
          text: "512"
        });
        const centerControls = controls.createDiv({
          cls: "wave-analyzer-center"
        });
        const timerDisplay = centerControls.createEl("span", {
          cls: "wave-analyzer-timer",
          text: "00:00:000"
        });
        controls.createDiv({ cls: "wave-analyzer-spacer" });
        playButton.type = "button";
        modeButton.type = "button";
        analysisButton.type = "button";
        resolutionButton.type = "button";
        playButton.setAttribute("aria-label", "Play");
        modeButton.setAttribute("aria-label", "Toggle waveform or spectrum");
        analysisButton.setAttribute(
          "aria-label",
          "Toggle centroid and harmonicity analysis"
        );
        resolutionButton.setAttribute(
          "aria-label",
          "Cycle spectrum resolution"
        );
        let visualizationMode = content.toLowerCase().includes("wave") ? "waveform" : "spectrum";
        let resolutionIndex = DEFAULT_RESOLUTION_INDEX;
        let analysisEnabled = false;
        let audioContext = null;
        let audioBuffer = null;
        let source = null;
        let animationFrame = null;
        let isPlaying = false;
        let isLooping = false;
        let isSelectingRegion = false;
        let isDraggingPlayhead = false;
        let resumeAfterDrag = false;
        let regionStart = 0;
        let regionEnd = 0;
        let playheadPosition = 0;
        let playbackOffset = 0;
        let playbackStartedAt = 0;
        let spectrogramData = [];
        let centroidSeries = [];
        let harmonicitySeries = [];
        let averageCentroid = 0;
        let averageHarmonicity = 0;
        let needsRedraw = true;
        let analysisRunId = 0;
        let isCleanedUp = false;
        const updateTimerDisplay = (position = null) => {
          const currentTime = typeof position === "number" ? position : currentPosition();
          const totalTime = audioBuffer ? audioBuffer.duration : 0;
          timerDisplay.textContent = `${formatTime(currentTime)} / ${formatTime(totalTime)}`;
        };
        const updatePlayButton = () => {
          playButton.innerHTML = isPlaying ? STOP_ICON : PLAY_ICON;
          playButton.classList.toggle("play", !isPlaying);
          playButton.classList.toggle("stop", isPlaying);
          playButton.setAttribute("aria-label", isPlaying ? "Stop" : "Play");
        };
        const updateAnalysisButton = () => {
          analysisButton.innerHTML = ANALYSIS_ICON;
          analysisButton.classList.toggle("is-active", analysisEnabled);
          analysisButton.setAttribute(
            "aria-label",
            analysisEnabled ? "Disable centroid and harmonicity analysis" : "Enable centroid and harmonicity analysis"
          );
          analysisButton.title = analysisEnabled ? "Analysis on" : "Analysis off";
        };
        const updateModeButton = () => {
          modeButton.textContent = visualizationMode === "waveform" ? "W" : "S";
          canvas.style.display = visualizationMode === "waveform" ? "block" : "none";
          spectrogram.style.display = visualizationMode === "spectrum" ? "block" : "none";
          updateRegion2();
        };
        const updateResolutionButton = () => {
          const resolution = RESOLUTION_OPTIONS[resolutionIndex];
          resolutionButton.textContent = `${resolution}`;
          resolutionButton.title = `FFT ${resolution}`;
        };
        const activeCanvas = () => visualizationMode === "waveform" ? canvas : spectrogram;
        const hasLoopRegion = () => {
          if (!audioBuffer) {
            return false;
          }
          return Math.abs(regionEnd - regionStart) > 1 / audioBuffer.sampleRate;
        };
        const currentPosition = () => {
          if (!audioBuffer) {
            return 0;
          }
          if (!isPlaying) {
            return clamp(playheadPosition, 0, audioBuffer.duration);
          }
          const elapsed = Math.max(
            0,
            audioContext.currentTime - playbackStartedAt
          );
          if (isLooping && hasLoopRegion()) {
            const loopStart = Math.min(regionStart, regionEnd);
            const loopEnd = Math.max(regionStart, regionEnd);
            const loopDuration = Math.max(
              loopEnd - loopStart,
              1 / audioBuffer.sampleRate
            );
            const relativeOffset = clamp(playbackOffset, loopStart, loopEnd) - loopStart;
            return loopStart + (relativeOffset + elapsed) % loopDuration;
          }
          return clamp(playbackOffset + elapsed, 0, audioBuffer.duration);
        };
        const setPlayhead = (seconds) => {
          if (!audioBuffer) {
            return;
          }
          playheadPosition = clamp(seconds, 0, audioBuffer.duration);
          playbackOffset = playheadPosition;
          updateTimerDisplay(playheadPosition);
          needsRedraw = true;
          drawVisualization();
        };
        const stopSource = (shouldStopNode) => {
          if (!source) {
            return;
          }
          source.onended = null;
          if (shouldStopNode) {
            try {
              source.stop();
            } catch (error) {
            }
          }
          try {
            source.disconnect();
          } catch (error) {
          }
          source = null;
        };
        const stopPlayback = ({
          resetPosition = false,
          finalPosition = null,
          stopNode = true
        } = {}) => {
          stopSource(stopNode);
          if (animationFrame) {
            cancelAnimationFrame(animationFrame);
            animationFrame = null;
          }
          isPlaying = false;
          if (audioBuffer) {
            if (resetPosition) {
              playheadPosition = 0;
            } else if (typeof finalPosition === "number") {
              playheadPosition = clamp(finalPosition, 0, audioBuffer.duration);
            }
            playbackOffset = playheadPosition;
            updateTimerDisplay(playheadPosition);
          } else {
            updateTimerDisplay(0);
          }
          updatePlayButton();
          needsRedraw = true;
          drawVisualization();
        };
        const renderFrame = () => {
          if (!isPlaying || !audioBuffer) {
            return;
          }
          playheadPosition = currentPosition();
          updateTimerDisplay(playheadPosition);
          needsRedraw = true;
          drawVisualization();
          animationFrame = requestAnimationFrame(renderFrame);
        };
        const playAudio = async (startAt = playheadPosition) => {
          if (!audioBuffer) {
            throw new Error("Audio buffer not loaded");
          }
          if (audioContext.state === "suspended") {
            await audioContext.resume();
          }
          stopSource(true);
          if (animationFrame) {
            cancelAnimationFrame(animationFrame);
            animationFrame = null;
          }
          source = audioContext.createBufferSource();
          source.buffer = audioBuffer;
          const loopActive = isLooping && hasLoopRegion();
          let startOffset = clamp(startAt, 0, audioBuffer.duration);
          if (loopActive) {
            const loopStart = Math.min(regionStart, regionEnd);
            const loopEnd = Math.max(regionStart, regionEnd);
            source.loop = true;
            source.loopStart = loopStart;
            source.loopEnd = loopEnd;
            if (startOffset < loopStart || startOffset >= loopEnd) {
              startOffset = loopStart;
            }
          } else {
            source.loop = false;
            if (startOffset >= audioBuffer.duration - 1 / audioBuffer.sampleRate) {
              startOffset = 0;
            }
          }
          playbackOffset = startOffset;
          playheadPosition = startOffset;
          playbackStartedAt = audioContext.currentTime;
          source.connect(audioContext.destination);
          source.start(0, startOffset);
          isPlaying = true;
          const activeSource = source;
          activeSource.onended = () => {
            if (source !== activeSource || activeSource.loop || isCleanedUp) {
              return;
            }
            stopPlayback({
              finalPosition: audioBuffer.duration,
              stopNode: false
            });
          };
          updatePlayButton();
          updateTimerDisplay(playheadPosition);
          needsRedraw = true;
          drawVisualization();
          renderFrame();
        };
        const getSeriesIndexForTime = (time) => {
          if (!audioBuffer || centroidSeries.length === 0) {
            return 0;
          }
          if (centroidSeries.length === 1 || audioBuffer.duration <= 0) {
            return 0;
          }
          return clamp(
            Math.round(
              time / audioBuffer.duration * (centroidSeries.length - 1)
            ),
            0,
            centroidSeries.length - 1
          );
        };
        const getMetricsAtTime = (time) => {
          var _a, _b;
          if (centroidSeries.length === 0) {
            return {
              centroid: averageCentroid,
              harmonicity: averageHarmonicity
            };
          }
          const index = getSeriesIndexForTime(time);
          return {
            centroid: (_a = centroidSeries[index]) != null ? _a : averageCentroid,
            harmonicity: (_b = harmonicitySeries[index]) != null ? _b : averageHarmonicity
          };
        };
        const drawSeriesLine = (ctx2, values, width, color, yMapper, dash) => {
          if (!values.length) {
            return;
          }
          ctx2.save();
          ctx2.beginPath();
          ctx2.strokeStyle = color;
          ctx2.lineWidth = 1.25;
          ctx2.setLineDash(dash);
          for (let i = 0; i < values.length; i++) {
            const x = values.length === 1 ? 0 : i / (values.length - 1) * width;
            const y = yMapper(values[i]);
            if (i === 0) {
              ctx2.moveTo(x, y);
            } else {
              ctx2.lineTo(x, y);
            }
          }
          ctx2.stroke();
          ctx2.restore();
        };
        const drawRulerGrid = (ctx2, width, height, textRgb, textColor) => {
          if (!audioBuffer) {
            return;
          }
          const duration = audioBuffer.duration;
          const maxSecond = Math.ceil(duration);
          ctx2.font = "7px monospace";
          ctx2.textBaseline = "top";
          for (let second = 0; second <= maxSecond; second++) {
            const x = duration > 0 ? second / duration * width : 0;
            const tickHeight = second % 10 === 0 ? 8 : second % 5 === 0 ? 5 : 3;
            ctx2.strokeStyle = alphaColor(textRgb, 0.6, "255, 255, 255");
            ctx2.lineWidth = 1;
            ctx2.beginPath();
            ctx2.moveTo(x + 0.5, RULER_HEIGHT - tickHeight);
            ctx2.lineTo(x + 0.5, RULER_HEIGHT);
            ctx2.stroke();
            if (second % 10 === 0) {
              const label = formatRulerTime(second);
              const alignedX = clamp(x - 7, 0, Math.max(0, width - 15));
              ctx2.fillStyle = alphaColor(textRgb, 0.6, "255, 255, 255");
              ctx2.fillText(label, alignedX, 1);
            }
          }
        };
        const drawMetricOverlay = (ctx2, width, height, currentMetrics, textColor, textRgb, backgroundRgb) => {
          if (!audioBuffer || !analysisEnabled || centroidSeries.length === 0) {
            return;
          }
          const plotTop = RULER_HEIGHT;
          const plotBottom = height;
          const plotHeight = plotBottom - plotTop;
          const nyquist = audioBuffer.sampleRate / 2;
          const centroidColor = "rgba(79, 209, 255, 0.5)";
          const harmonicityColor = "rgba(255, 179, 71, 0.5)";
          drawSeriesLine(
            ctx2,
            centroidSeries,
            width,
            centroidColor,
            (value) => plotBottom - clamp(value / nyquist, 0, 1) * plotHeight,
            []
          );
          drawSeriesLine(
            ctx2,
            harmonicitySeries,
            width,
            harmonicityColor,
            (value) => plotBottom - clamp(value, 0, 1) * plotHeight,
            [4, 3]
          );
          const metricIndex = getSeriesIndexForTime(currentPosition());
          const metricX = centroidSeries.length > 1 ? metricIndex / (centroidSeries.length - 1) * width : 0;
          const centroidY = plotBottom - clamp(currentMetrics.centroid / nyquist, 0, 1) * plotHeight;
          const harmonicityY = plotBottom - clamp(currentMetrics.harmonicity, 0, 1) * plotHeight;
          ctx2.save();
          ctx2.fillStyle = centroidColor;
          ctx2.beginPath();
          ctx2.arc(metricX, centroidY, 2.5, 0, 2 * Math.PI);
          ctx2.fill();
          ctx2.fillStyle = harmonicityColor;
          ctx2.beginPath();
          ctx2.arc(metricX, harmonicityY, 2.5, 0, 2 * Math.PI);
          ctx2.fill();
          ctx2.restore();
          ctx2.save();
          ctx2.fillStyle = alphaColor(backgroundRgb, 0.78, "0, 0, 0");
          ctx2.fillRect(8, plotTop + 6, 228, 34);
          ctx2.font = "11px monospace";
          ctx2.textBaseline = "middle";
          ctx2.fillStyle = centroidColor;
          ctx2.fillText("Centroid", 14, plotTop + 17);
          ctx2.fillStyle = textColor;
          ctx2.fillText(
            `${Math.round(currentMetrics.centroid)}Hz avg ${Math.round(averageCentroid)}Hz`,
            76,
            plotTop + 17
          );
          ctx2.fillStyle = harmonicityColor;
          ctx2.fillText("Harm", 14, plotTop + 31);
          ctx2.fillStyle = textColor;
          ctx2.fillText(
            `${currentMetrics.harmonicity.toFixed(2)} avg ${averageHarmonicity.toFixed(2)}`,
            76,
            plotTop + 31
          );
          ctx2.strokeStyle = alphaColor(textRgb, 0.12, "255, 255, 255");
          ctx2.strokeRect(8.5, plotTop + 6.5, 227, 33);
          ctx2.restore();
        };
        const drawWaveform = (ctx2, width, height, textColor) => {
          const data = audioBuffer.getChannelData(0);
          const plotTop = RULER_HEIGHT;
          const plotHeight = height - plotTop;
          const midY = plotTop + plotHeight / 2;
          const amplitude = plotHeight / 2 - 4;
          ctx2.beginPath();
          ctx2.strokeStyle = textColor;
          ctx2.lineWidth = 1;
          for (let x = 0; x < width; x++) {
            const start = Math.floor(x / width * data.length);
            const end = Math.max(
              start + 1,
              Math.floor((x + 1) / width * data.length)
            );
            let min = 1;
            let max = -1;
            for (let i = start; i < end; i++) {
              const value = data[i];
              if (value < min) {
                min = value;
              }
              if (value > max) {
                max = value;
              }
            }
            ctx2.moveTo(x + 0.5, midY + min * amplitude);
            ctx2.lineTo(x + 0.5, midY + max * amplitude);
          }
          ctx2.stroke();
        };
        const drawSpectrogram = (ctx2, width, height) => {
          if (!spectrogramData.length) {
            return;
          }
          const plotTop = RULER_HEIGHT;
          const plotHeight = height - plotTop;
          const frameWidth = width / spectrogramData.length;
          for (let frameIndex = 0; frameIndex < spectrogramData.length; frameIndex++) {
            const bins = spectrogramData[frameIndex];
            const x = frameIndex * frameWidth;
            for (let y = 0; y < plotHeight; y++) {
              const fromBin = Math.floor(y / plotHeight * bins.length);
              const toBin = Math.max(
                fromBin + 1,
                Math.floor((y + 1) / plotHeight * bins.length)
              );
              let peakDb = -100;
              for (let bin = fromBin; bin < toBin; bin++) {
                peakDb = Math.max(peakDb, bins[bin]);
              }
              const intensity = clamp((peakDb + 95) / 95, 0, 1);
              const hue = 220 - intensity * 210;
              ctx2.fillStyle = `hsla(${hue}, 90%, ${28 + intensity * 30}%, ${0.18 + intensity * 0.82})`;
              ctx2.fillRect(
                x,
                plotTop + plotHeight - y - 1,
                Math.ceil(frameWidth) + 1,
                1
              );
            }
          }
        };
        const drawPlaybar = (ctx2, width, height) => {
          if (!audioBuffer) {
            return;
          }
          const position = currentPosition();
          const x = audioBuffer.duration > 0 ? clamp(position / audioBuffer.duration * width, 0, width) : 0;
          ctx2.save();
          ctx2.globalCompositeOperation = "difference";
          ctx2.fillStyle = "#ffffff";
          ctx2.fillRect(x - PLAYBAR_WIDTH / 2, 0, PLAYBAR_WIDTH, height);
          ctx2.restore();
        };
        const drawVisualization = () => {
          if (!audioBuffer || !needsRedraw) {
            return;
          }
          const surface = activeCanvas();
          const dpr = window.devicePixelRatio || 1;
          const width = surface.width / dpr;
          const height = surface.height / dpr;
          const ctx2 = surface.getContext("2d");
          const styles = getComputedStyle(document.body);
          const textColor = styles.getPropertyValue("--text-normal").trim() || "#ffffff";
          const textRgb = styles.getPropertyValue("--text-normal-rgb").trim();
          const backgroundRgb = styles.getPropertyValue("--background-primary-rgb").trim();
          const canvasBg = getComputedStyle(container).getPropertyValue("--canvas-bg").trim() || "transparent";
          ctx2.clearRect(0, 0, width, height);
          ctx2.fillStyle = canvasBg;
          ctx2.fillRect(0, 0, width, height);
          drawRulerGrid(ctx2, width, height, textRgb, textColor);
          if (visualizationMode === "waveform") {
            drawWaveform(ctx2, width, height, textColor);
          } else {
            drawSpectrogram(ctx2, width, height);
          }
          drawMetricOverlay(
            ctx2,
            width,
            height,
            getMetricsAtTime(currentPosition()),
            textColor,
            textRgb,
            backgroundRgb
          );
          drawPlaybar(ctx2, width, height);
          needsRedraw = false;
        };
        const applyFullWidthLayout = () => {
          const host = container.closest(".view-content") || container.closest(".markdown-reading-view") || container.closest(".markdown-preview-view") || container.parentElement;
          const anchor = container.parentElement;
          if (!host || !anchor) {
            return;
          }
          const hostRect = host.getBoundingClientRect();
          const anchorRect = anchor.getBoundingClientRect();
          const fullWidth = Math.max(hostRect.width - 16, anchorRect.width);
          const offsetLeft = hostRect.left - anchorRect.left + 8;
          container.style.width = `${fullWidth}px`;
          container.style.maxWidth = `${fullWidth}px`;
          container.style.minWidth = `${fullWidth}px`;
          container.style.marginLeft = `${offsetLeft}px`;
          container.style.marginRight = "0";
        };
        const resize = () => {
          applyFullWidthLayout();
          const rect = stage.getBoundingClientRect();
          const dpr = window.devicePixelRatio || 1;
          [canvas, spectrogram].forEach((surface) => {
            surface.width = rect.width * dpr;
            surface.height = rect.height * dpr;
            surface.style.width = `${rect.width}px`;
            surface.style.height = `${rect.height}px`;
            const ctx2 = surface.getContext("2d");
            ctx2.setTransform(1, 0, 0, 1, 0, 0);
            ctx2.scale(dpr, dpr);
            ctx2.imageSmoothingEnabled = false;
          });
          needsRedraw = true;
          updateRegion2();
          drawVisualization();
        };
        const runAnalysis = async (buffer) => {
          const currentRunId = ++analysisRunId;
          const requestedFftSize = RESOLUTION_OPTIONS[resolutionIndex];
          const fftSize = Math.min(
            requestedFftSize,
            highestPowerOfTwo(buffer.length)
          );
          const channelData = buffer.getChannelData(0);
          const sampleRate = buffer.sampleRate;
          const stageWidth = Math.max(
            Math.floor(stage.getBoundingClientRect().width || 320),
            160
          );
          const frameTarget = Math.max(72, Math.min(stageWidth, 180));
          const lastStart = Math.max(channelData.length - fftSize, 0);
          const hopSize = frameTarget > 1 ? Math.max(
            1,
            Math.floor(lastStart / (frameTarget - 1) || fftSize / 2)
          ) : fftSize;
          const frameCount = Math.max(
            1,
            Math.min(frameTarget, Math.floor(lastStart / hopSize) + 1)
          );
          const windowValues = createHannWindow(fftSize);
          const nextSpectrogram = [];
          const nextCentroidSeries = [];
          const nextHarmonicitySeries = [];
          let centroidWeightTotal = 0;
          let centroidWeightedSum = 0;
          let harmonicityWeightTotal = 0;
          let harmonicityWeightedSum = 0;
          for (let frameIndex = 0; frameIndex < frameCount; frameIndex++) {
            if (currentRunId !== analysisRunId || isCleanedUp) {
              return;
            }
            const start = Math.min(frameIndex * hopSize, lastStart);
            const real = new Float32Array(fftSize);
            const imag = new Float32Array(fftSize);
            for (let i = 0; i < fftSize; i++) {
              real[i] = (channelData[start + i] || 0) * windowValues[i];
            }
            fft(real, imag);
            const half = fftSize / 2;
            const dbBins = new Float32Array(half);
            const powerBins = new Float32Array(half);
            let totalPower = 0;
            let weightedFrequency = 0;
            for (let bin = 1; bin < half; bin++) {
              const magnitudeSquared = real[bin] * real[bin] + imag[bin] * imag[bin];
              powerBins[bin] = magnitudeSquared;
              dbBins[bin] = clamp(
                10 * Math.log10(magnitudeSquared + 1e-12),
                -100,
                0
              );
              totalPower += magnitudeSquared;
              weightedFrequency += bin * sampleRate / fftSize * magnitudeSquared;
            }
            nextSpectrogram.push(dbBins);
            if (analysisEnabled) {
              const centroid = totalPower > 0 ? weightedFrequency / totalPower : 0;
              const harmonicity = estimateHarmonicity(
                powerBins,
                sampleRate,
                fftSize,
                totalPower
              );
              nextCentroidSeries.push(centroid);
              nextHarmonicitySeries.push(harmonicity);
              if (totalPower > 0) {
                centroidWeightedSum += centroid * totalPower;
                centroidWeightTotal += totalPower;
                harmonicityWeightedSum += harmonicity * totalPower;
                harmonicityWeightTotal += totalPower;
              }
            }
          }
          if (currentRunId !== analysisRunId || isCleanedUp) {
            return;
          }
          spectrogramData = nextSpectrogram;
          centroidSeries = analysisEnabled ? smoothSeries(nextCentroidSeries, 3) : [];
          harmonicitySeries = analysisEnabled ? smoothSeries(nextHarmonicitySeries, 3) : [];
          averageCentroid = analysisEnabled && centroidWeightTotal > 0 ? centroidWeightedSum / centroidWeightTotal : 0;
          averageHarmonicity = analysisEnabled && harmonicityWeightTotal > 0 ? harmonicityWeightedSum / harmonicityWeightTotal : 0;
          needsRedraw = true;
          drawVisualization();
        };
        const pointerPositionToTime = (event, surface) => {
          if (!audioBuffer) {
            return 0;
          }
          const rect = surface.getBoundingClientRect();
          const x = clamp(event.clientX - rect.left, 0, rect.width);
          return rect.width > 0 ? x / rect.width * audioBuffer.duration : 0;
        };
        const updateTooltip = (event, surface) => {
          if (!analysisEnabled) {
            tooltip.style.display = "none";
            return;
          }
          const rect = surface.getBoundingClientRect();
          const x = event.clientX - rect.left;
          const y = event.clientY - rect.top;
          const insideMetrics = x >= 8 && x <= 236 && y >= RULER_HEIGHT + 6 && y <= RULER_HEIGHT + 40;
          if (!insideMetrics) {
            tooltip.style.display = "none";
            return;
          }
          tooltip.textContent = "Centroid = spectral balance. Harmonicity = harmonic peak ratio. Drag to seek, Shift+drag in waveform to loop.";
          tooltip.style.left = `${Math.max(8, Math.min(rect.width - 220, x + 10))}px`;
          tooltip.style.top = `${Math.max(8, Math.min(rect.height - 52, y + 10))}px`;
          tooltip.style.display = "block";
        };
        const handlePointerDown = (event) => {
          if (!audioBuffer) {
            return;
          }
          if (event.button !== 0) {
            return;
          }
          const surface = event.currentTarget;
          if (surface.setPointerCapture) {
            surface.setPointerCapture(event.pointerId);
          }
          if (visualizationMode === "waveform" && event.shiftKey) {
            isSelectingRegion = true;
            isLooping = false;
            regionStart = pointerPositionToTime(event, surface);
            regionEnd = regionStart;
            updateRegion2();
            return;
          }
          resumeAfterDrag = isPlaying;
          if (isPlaying) {
            stopPlayback({ finalPosition: currentPosition() });
          }
          isDraggingPlayhead = true;
          setPlayhead(pointerPositionToTime(event, surface));
        };
        const handlePointerMove = (event) => {
          const surface = event.currentTarget;
          if (isSelectingRegion) {
            regionEnd = pointerPositionToTime(event, surface);
            updateRegion2();
            return;
          }
          if (isDraggingPlayhead) {
            setPlayhead(pointerPositionToTime(event, surface));
            return;
          }
          updateTooltip(event, surface);
        };
        const handlePointerUp = (event) => {
          const surface = event.currentTarget;
          if (surface.releasePointerCapture && surface.hasPointerCapture(event.pointerId)) {
            surface.releasePointerCapture(event.pointerId);
          }
          if (isSelectingRegion) {
            const resumePosition = currentPosition();
            isSelectingRegion = false;
            isLooping = hasLoopRegion();
            updateRegion2();
            if (isPlaying) {
              playAudio(resumePosition).catch(() => {
                timerDisplay.textContent = "Playback error";
              });
            }
            return;
          }
          if (!isDraggingPlayhead) {
            return;
          }
          isDraggingPlayhead = false;
          tooltip.style.display = "none";
          if (resumeAfterDrag) {
            resumeAfterDrag = false;
            playAudio(playheadPosition).catch(() => {
              timerDisplay.textContent = "Playback error";
            });
          }
        };
        const handlePointerLeave = () => {
          if (!isDraggingPlayhead && !isSelectingRegion) {
            tooltip.style.display = "none";
          }
        };
        const resizeHandler = /* @__PURE__ */ (() => {
          let timeout = null;
          return () => {
            if (timeout) {
              window.clearTimeout(timeout);
            }
            timeout = window.setTimeout(() => {
              timeout = null;
              resize();
            }, 100);
          };
        })();
        updatePlayButton();
        updateAnalysisButton();
        updateModeButton();
        updateResolutionButton();
        playButton.addEventListener("click", () => {
          if (isPlaying) {
            stopPlayback({ resetPosition: true });
            return;
          }
          playAudio(playheadPosition).catch(() => {
            timerDisplay.textContent = "Playback error";
          });
        });
        modeButton.addEventListener("click", () => {
          visualizationMode = visualizationMode === "waveform" ? "spectrum" : "waveform";
          updateModeButton();
          needsRedraw = true;
          drawVisualization();
        });
        analysisButton.addEventListener("click", async () => {
          analysisEnabled = !analysisEnabled;
          updateAnalysisButton();
          tooltip.style.display = "none";
          if (!audioBuffer) {
            needsRedraw = true;
            drawVisualization();
            return;
          }
          await runAnalysis(audioBuffer);
        });
        resolutionButton.addEventListener("click", async () => {
          if (!audioBuffer) {
            return;
          }
          resolutionIndex = (resolutionIndex + 1) % RESOLUTION_OPTIONS.length;
          updateResolutionButton();
          await runAnalysis(audioBuffer);
        });
        [canvas, spectrogram].forEach((surface) => {
          surface.addEventListener("pointerdown", handlePointerDown);
          surface.addEventListener("pointermove", handlePointerMove);
          surface.addEventListener("pointerup", handlePointerUp);
          surface.addEventListener("pointerleave", handlePointerLeave);
        });
        window.addEventListener("resize", resizeHandler);
        const observer = new MutationObserver(() => {
          needsRedraw = true;
          drawVisualization();
        });
        observer.observe(document.documentElement, {
          attributes: true,
          attributeFilter: ["data-theme"]
        });
        audioContext = new (window.AudioContext || window.webkitAudioContext)();
        timerDisplay.textContent = "Loading audio... / --:--:---";
        try {
          const audioBinary = await this.app.vault.adapter.readBinary(
            linkpath.path
          );
          audioBuffer = await audioContext.decodeAudioData(
            audioBinary.slice(0)
          );
          updateTimerDisplay(0);
          resize();
          await runAnalysis(audioBuffer);
          setPlayhead(0);
        } catch (error) {
          timerDisplay.textContent = "Audio decode error";
          observer.disconnect();
          window.removeEventListener("resize", resizeHandler);
          if (audioContext && audioContext.state !== "closed") {
            audioContext.close().catch(() => {
            });
          }
          return;
        }
        const cleanup = () => {
          if (isCleanedUp) {
            return;
          }
          isCleanedUp = true;
          analysisRunId += 1;
          tooltip.style.display = "none";
          window.removeEventListener("resize", resizeHandler);
          observer.disconnect();
          if (animationFrame) {
            cancelAnimationFrame(animationFrame);
            animationFrame = null;
          }
          stopSource(true);
          if (audioContext && audioContext.state !== "closed") {
            audioContext.close().catch(() => {
            });
          }
        };
        ctx.addChild(new WaveAnalyzerRenderChild(container, cleanup));
      } catch (error) {
        el.createEl("div", {
          cls: "wave-analyzer-error",
          text: `Error: ${error.message}`
        });
      }
    });
  }
  injectStyles() {
    const existingStyle = document.getElementById(STYLE_ID);
    if (existingStyle) {
      return;
    }
    const style = document.createElement("style");
    style.id = STYLE_ID;
    style.textContent = `
      .wave-analyzer-container {
        display: flex;
        flex-direction: column;
        gap: 6px;
        width: 100%;
        max-width: 100%;
        padding: 0;
        margin: 0;
        box-sizing: border-box;
      }

      .wave-analyzer-stage {
        position: relative;
        width: 100%;
        height: ${CANVAS_HEIGHT}px;
        overflow: hidden;
      }

      .wave-analyzer-canvas,
      .wave-analyzer-spectrogram {
        position: absolute;
        inset: 0;
        width: 100%;
        height: 100%;
        cursor: col-resize;
      }

      .wave-analyzer-region {
        position: absolute;
        top: ${RULER_HEIGHT}px;
        height: calc(100% - ${RULER_HEIGHT}px);
        background: rgba(var(--text-normal-rgb), 0.14);
        border: 1px solid rgba(var(--text-normal-rgb), 0.35);
        pointer-events: none;
        z-index: 3;
        display: none;
      }

      .wave-analyzer-controls {
        display: grid;
        grid-template-columns: 1fr auto 1fr;
        gap: 10px;
        align-items: center;
        width: 100%;
      }

      .wave-analyzer-buttons {
        display: flex;
        align-items: center;
        gap: 8px;
        justify-content: flex-start;
      }

      .wave-analyzer-center {
        display: flex;
        justify-content: center;
      }

      .wave-analyzer-spacer {
        min-width: 1px;
      }

      .wave-analyzer-controls button {
        display: inline-flex;
        align-items: center;
        justify-content: center;
        min-width: 28px;
        height: 24px;
        padding: 0 4px;
        background: none;
        border: none;
        box-shadow: none;
        color: var(--text-normal);
        cursor: pointer;
        opacity: 0.78;
        font: 11px/1 monospace;
        letter-spacing: 0.06em;
      }

      .wave-analyzer-controls button:hover {
        opacity: 1;
        background: none;
        box-shadow: none;
      }

      .wave-analyzer-controls button:focus-visible {
        outline: 1px solid rgba(var(--text-normal-rgb), 0.35);
        outline-offset: 2px;
      }

      .wave-analyzer-play.play {
        color: #53ff8c;
        opacity: 1;
      }

      .wave-analyzer-play.stop {
        color: var(--text-normal);
        opacity: 1;
      }

      .wave-analyzer-play {
        min-width: 72px;
        width: 72px;
        height: 72px;
        margin-right: 4px;
        padding: 0;
      }

      .wave-analyzer-analysis {
        min-width: 56px;
        width: 56px;
        height: 56px;
        padding: 0;
      }

      .wave-analyzer-analysis.is-active {
        color: #6edcff;
        opacity: 1;
      }

      .wave-analyzer-play svg {
        width: 32px;
        height: 32px;
        fill: currentColor;
      }

      .wave-analyzer-analysis svg {
        width: 36px;
        height: 36px;
        fill: currentColor;
      }

      .wave-analyzer-timer {
        font: 11px monospace;
        color: var(--text-normal);
        text-align: center;
      }

      .wave-analyzer-tooltip {
        position: absolute;
        max-width: 210px;
        padding: 6px 8px;
        border-radius: 4px;
        background: var(--background-secondary);
        color: var(--text-normal);
        font: 10px/1.35 monospace;
        pointer-events: none;
        z-index: 10;
        display: none;
      }

      .wave-analyzer-error {
        color: var(--text-error);
      }

      :root {
        --canvas-bg: transparent;
      }

      body.theme-dark .wave-analyzer-container {
        --canvas-bg: rgba(0, 0, 0, 0.08);
      }

      body.theme-light .wave-analyzer-container {
        --canvas-bg: rgba(255, 255, 255, 0.15);
      }
    `;
    document.head.appendChild(style);
    this.register(() => {
      style.remove();
    });
  }
};
